### ISSUE TITLE
Suggested adjustments to the repo structure

### ISSUE THREAD

**Issue by swcurran** [petridishdev/aries-acapy-controllers#5]
Hey @amanji - looking awesome!!  Love it!

I'd like to propose a few tweaks to the structure/folder names so that other examples can be added as well.  Please take a look and let me know what you think:

- rename "/demo" to "/AliceFaberDemo"
- Move the current README.md to the "AliceFaberDemo" folder
- Add a new, top of repo README.md that is more general, with an overview paragraph of what the the AliceFaberDemo is and a link to run it. It will have additional content like contributions guide, etc.
- Move ".docker" to with AliceFaberDemo, and call it "docker"
- Add a start up option "logs" (to go with "webstart", "webdown") that runs docker-compose -f <> logs

I'd be glad to make those adjustments if they make sense to you.

**Comment by amanji** [comment]
@swcurran

Just need some clarification for:

>Add a start up option "logs" (to go with "webstart", "webdown") that runs docker-compose -f <> logs

Should this be a separate option that outputs the logs for an already running service ie. `./run_demo logs`, or should it be a parameter passed to `webstart` that would essentially run the service in attached mode ie. `./run_demo webstart --logs`, or perhaps the latter option but in detached mode with log output to the terminal?

**Comment by swcurran** [comment]
We're having the same discussion on von-network.  I think the best approach is the following:

- have webstart use the -d option and do not show any logs.
- have an option --logs to webstart that immediately after running webstart does a "docker-compose logs" so that the user can see the logs
- have a separate option from webstart called "logs" that can be used if the user does NOT use --logs, but later wants to watch the logs.

Does that make sense?

I suspect there is an option (perhaps "--tail"?) to `docker-compose logs` such that the logs continue vs. just listing the existing logs.  It would be that "tail" mechanism that we would want to use, with ctrl-c to break out of the tailing of the logs.

**Comment by swcurran** [comment]
BTW - I tweaked my answer above a little on the first two points to make it clear when I mean an option to ./manage and when I mean a docker-compose option.

**Comment by amanji** [comment]
If this looks good, can I close the issue?

**Comment by swcurran** [comment]
Yup - looks great.  Nice work!
